# For possible options see https://peps.python.org/pep-0621/
 
[project]
name = "busker"
dynamic = ["version"]
description = "A utility for testing Balladeer projects."
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
keywords = ["interactive fiction", "balladeer"]
authors = [
    {name = "D E Haynes", email = "tundish@gigeconomy.org.uk"}
]
maintainers = [
    {name = "Tundish", email = "tundish@gigeconomy.org.uk"}
]
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Development Status :: 4 - Beta",
]
dependencies = [
]

[project.optional-dependencies]
test = [
]

[project.scripts]
busker-gui = "busker.gui.main:run"
busker-stagegraph = "busker.utils.graph:run"

[build-system]
requires = ["setuptools>=75.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "busker",
    "busker.core",
    "busker.core.test",
    "busker.data",
    "busker.engine",
    "busker.engine.test",
    "busker.gui",
    "busker.gui.test",
    "busker.model",
    "busker.model.test",
    "busker.plugins",
    "busker.plugins.test",
    "busker.utils",
]

[tool.setuptools.package-data]
"busker.test" = [
    "*/*.toml",
]

[tool.setuptools.dynamic]
version = {attr = "busker.__version__"}
